project_id = "ihxczttkofjnyviqmxpl"

[functions.invite-socio]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.baja-socio]
verify_jwt = false

[functions.notify-socios]
verify_jwt = false

[functions.send-notificacion]
verify_jwt = false

[functions.og-news]
verify_jwt = false

[functions.notify-new-solicitud]
verify_jwt = false
