project_id = "ihxczttkofjnyviqmxpl"

[functions.invite-socio]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.resend-sepa]
verify_jwt = false

[functions.baja-socio]
verify_jwt = false

[functions.notify-socios]
verify_jwt = false

[functions.send-notificacion]
verify_jwt = false

[functions.og-news]
verify_jwt = false

[functions.notify-new-solicitud]
verify_jwt = false

[functions.certificado-voto]
verify_jwt = false

[functions.publish-scheduled-news]
verify_jwt = false

[functions.certificado-resultados]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false

[functions.notify-calendario-junta]
verify_jwt = false

[functions.calendario-reminder]
verify_jwt = false

[functions.notify-exclusive-news]
verify_jwt = false

[functions.send-sepa-update]
verify_jwt = false

[functions.send-mailing]
verify_jwt = false
